export default {
    PLATE: require("../assets/images/plate.png"),
    DELIVER: require("../assets/images/deliver.png"),
    DISCOVER: require("../assets/images/discover.png"),
    FAVORITE: require("../assets/images/favorite.png"),
    FACEBOOK: require("../assets/images/facebook.png"),
    GOOGLE: require("../assets/images/google.png"),
    LOADING: require("../assets/images/12.gif"),
    FRIED_CHICKEN: require('../assets/images/fried_chicken.png'),
    BURGER: require('../assets/images/burger.png'),
    PIZZA: require('../assets/images/pizza.png'),
    DESSERT: require('../assets/images/dessert.png'),
    NOODLES: require('../assets/images/noodles.png'),
    DRINKS: require('../assets/images/drinks.png'),
    DELIVERY_TIME: require('../assets/images/delivery_time.png'),
    DELIVERY_CHARGE: require('../assets/images/delivery_charge.png'),
    MARKER: require('../assets/images/marker.png'),
    EMPTY_CART: require('../assets/images/empty_cart.png'),
    AVATAR: require('../assets/images/user_avatar.png'),


    BACKICON: require("../assets/images/backicon.png"),
    USERICON: require("../assets/images/usericon.png"),
    LOCKICON: require("../assets/images/lockicon.png"),
    EYEICON: require("../assets/images/eyeicon.png"),
    EYEOFF: require("../assets/images/eyeoff.png"),
    EMAIL: require("../assets/images/emailicon.png"),
    ARROWDOWN: require("../assets/images/arrowdownicon.png"),
    TICKMARK: require("../assets/images/icons8-tick-16.png"),
    XMARK: require("../assets/images/icons8-x-16.png"),
    LOCATION: require("../assets/images/location.png"),
    BELL: require("../assets/images/bell.png"),
    WHITEARROEDOWN: require("../assets/images/white-arrow-down.png"),
    SEARCH: require("../assets/images/search.png"),
    SLIDER: require("../assets/images/slider.png"),
    STAR: require("../assets/images/star.png"),
    YELLOWLOCATION: require("../assets/images/yellowlocation.png"),
    TIME: require("../assets/images/time.png"),

    

}
